# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddFriendPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddFriendPage(object):
    def setupUi(self, AddFriendPage):
        AddFriendPage.setObjectName("AddFriendPage")
        AddFriendPage.resize(640, 480)
        self.gridLayout = QtWidgets.QGridLayout(AddFriendPage)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(AddFriendPage)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.addFriendButton = QtWidgets.QPushButton(self.widget_2)
        self.addFriendButton.setObjectName("addFriendButton")
        self.gridLayout_2.addWidget(self.addFriendButton, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.addFriendUsernameInput = QtWidgets.QLineEdit(self.widget)
        self.addFriendUsernameInput.setObjectName("addFriendUsernameInput")
        self.horizontalLayout.addWidget(self.addFriendUsernameInput)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.addFriendStatusLabel = QtWidgets.QLabel(self.widget_2)
        self.addFriendStatusLabel.setText("")
        self.addFriendStatusLabel.setObjectName("addFriendStatusLabel")
        self.gridLayout_2.addWidget(self.addFriendStatusLabel, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_2, 1, 1, 1, 1)

        self.retranslateUi(AddFriendPage)
        QtCore.QMetaObject.connectSlotsByName(AddFriendPage)

    def retranslateUi(self, AddFriendPage):
        _translate = QtCore.QCoreApplication.translate
        AddFriendPage.setWindowTitle(_translate("AddFriendPage", "Form"))
        self.addFriendButton.setText(_translate("AddFriendPage", "Add Friend"))
        self.label.setText(_translate("AddFriendPage", "Username"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddFriendPage = QtWidgets.QWidget()
    ui = Ui_AddFriendPage()
    ui.setupUi(AddFriendPage)
    AddFriendPage.show()
    sys.exit(app.exec_())
