# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChatPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatPage(object):
    def setupUi(self, ChatPage):
        ChatPage.setObjectName("ChatPage")
        ChatPage.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(ChatPage)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.friendsListWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.friendsListWidget.sizePolicy().hasHeightForWidth())
        self.friendsListWidget.setSizePolicy(sizePolicy)
        self.friendsListWidget.setObjectName("friendsListWidget")
        self.friendsListLayout = QtWidgets.QVBoxLayout(self.friendsListWidget)
        self.friendsListLayout.setContentsMargins(0, 0, 0, 0)
        self.friendsListLayout.setObjectName("friendsListLayout")
        self.addFriendButton = QtWidgets.QPushButton(self.friendsListWidget)
        self.addFriendButton.setObjectName("addFriendButton")
        self.friendsListLayout.addWidget(self.addFriendButton)
        self.searchLineEdit = QtWidgets.QLineEdit(self.friendsListWidget)
        self.searchLineEdit.setToolTip("")
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.friendsListLayout.addWidget(self.searchLineEdit)
        self.line = QtWidgets.QFrame(self.friendsListWidget)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.friendsListLayout.addWidget(self.line)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.friendsListLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.friendsListWidget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.messageLineEdit = QtWidgets.QLineEdit(self.widget_3)
        self.messageLineEdit.setObjectName("messageLineEdit")
        self.horizontalLayout.addWidget(self.messageLineEdit)
        self.sendMessageButton = QtWidgets.QPushButton(self.widget_3)
        self.sendMessageButton.setEnabled(True)
        self.sendMessageButton.setObjectName("sendMessageButton")
        self.horizontalLayout.addWidget(self.sendMessageButton)
        self.gridLayout_2.addWidget(self.widget_3, 1, 0, 1, 1)
        self.messagesArea = QtWidgets.QScrollArea(self.widget_2)
        self.messagesArea.setWidgetResizable(True)
        self.messagesArea.setObjectName("messagesArea")
        self.messagesContainer = QtWidgets.QWidget()
        self.messagesContainer.setGeometry(QtCore.QRect(0, 0, 474, 407))
        self.messagesContainer.setObjectName("messagesContainer")
        self.messagesContainerLayout = QtWidgets.QVBoxLayout(self.messagesContainer)
        self.messagesContainerLayout.setObjectName("messagesContainerLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.messagesContainerLayout.addItem(spacerItem1)
        self.messagesArea.setWidget(self.messagesContainer)
        self.gridLayout_2.addWidget(self.messagesArea, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_2, 0, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 1, 1, 1)
        ChatPage.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(ChatPage)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 640, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuAccount = QtWidgets.QMenu(self.menuBar)
        self.menuAccount.setObjectName("menuAccount")
        ChatPage.setMenuBar(self.menuBar)
        self.changeAccountAction = QtWidgets.QAction(ChatPage)
        self.changeAccountAction.setObjectName("changeAccountAction")
        self.menuAccount.addAction(self.changeAccountAction)
        self.menuBar.addAction(self.menuAccount.menuAction())

        self.retranslateUi(ChatPage)
        QtCore.QMetaObject.connectSlotsByName(ChatPage)

    def retranslateUi(self, ChatPage):
        _translate = QtCore.QCoreApplication.translate
        ChatPage.setWindowTitle(_translate("ChatPage", "MainWindow"))
        self.addFriendButton.setText(_translate("ChatPage", "Add Friend"))
        self.searchLineEdit.setPlaceholderText(_translate("ChatPage", "Search User or Group"))
        self.messageLineEdit.setPlaceholderText(_translate("ChatPage", "Message"))
        self.sendMessageButton.setText(_translate("ChatPage", "Send"))
        self.menuAccount.setTitle(_translate("ChatPage", "Account"))
        self.changeAccountAction.setText(_translate("ChatPage", "Change Account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChatPage = QtWidgets.QMainWindow()
    ui = Ui_ChatPage()
    ui.setupUi(ChatPage)
    ChatPage.show()
    sys.exit(app.exec_())
