# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(752, 571)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.ip_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.ip_lineEdit.setObjectName("ip_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ip_lineEdit)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.port_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.port_lineEdit.setObjectName("port_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.port_lineEdit)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 2)
        self.openServer_button = QtWidgets.QPushButton(self.centralwidget)
        self.openServer_button.setObjectName("openServer_button")
        self.gridLayout.addWidget(self.openServer_button, 1, 1, 1, 1)
        self.closeServer_button = QtWidgets.QPushButton(self.centralwidget)
        self.closeServer_button.setEnabled(False)
        self.closeServer_button.setObjectName("closeServer_button")
        self.gridLayout.addWidget(self.closeServer_button, 1, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 1, 1, 2)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.disconnectClient_button = QtWidgets.QPushButton(self.frame_2)
        self.disconnectClient_button.setEnabled(False)
        self.disconnectClient_button.setObjectName("disconnectClient_button")
        self.gridLayout_2.addWidget(self.disconnectClient_button, 0, 1, 1, 1)
        self.clientsTable = QtWidgets.QTableWidget(self.frame_2)
        self.clientsTable.setEnabled(True)
        self.clientsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.clientsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.clientsTable.setTextElideMode(QtCore.Qt.ElideRight)
        self.clientsTable.setShowGrid(True)
        self.clientsTable.setObjectName("clientsTable")
        self.clientsTable.setColumnCount(2)
        self.clientsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.clientsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.clientsTable.setHorizontalHeaderItem(1, item)
        self.clientsTable.horizontalHeader().setVisible(True)
        self.clientsTable.horizontalHeader().setHighlightSections(True)
        self.clientsTable.horizontalHeader().setSortIndicatorShown(True)
        self.clientsTable.horizontalHeader().setStretchLastSection(True)
        self.clientsTable.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.clientsTable, 0, 0, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 4, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "IP"))
        self.label_2.setText(_translate("MainWindow", "PORT"))
        self.openServer_button.setText(_translate("MainWindow", "OPEN"))
        self.closeServer_button.setText(_translate("MainWindow", "CLOSE"))
        self.disconnectClient_button.setText(_translate("MainWindow", "DISCONNECT"))
        self.clientsTable.setSortingEnabled(True)
        item = self.clientsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.clientsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
